[deps]
CUTEst = "1b53aba6-35b6-5f92-a507-53c67d53f819"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsAlgencan = "04216931-dc08-4b80-8a27-8a88dc4b9604"
NLPModelsJuMP = "792afdf1-32c1-5681-94e0-d7bf7a5df49e"
